# Generated by Django 5.2.1 on 2025-05-30 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Место в котором небходимо выполнять привычку",
                        max_length=100,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Время когда необходимо выполнять привычку",
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Действие которое представляет собой привычка",
                        max_length=100,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        help_text="Привычка, которую можно привязать к выполнению полезной привычки.",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("m x-y * * *", "every hour"),
                            ("m x-y/2 * * *", "every 2 hours"),
                            ("m x-y/3 * * *", "every 3 hours"),
                            ("m x,z,y * * *", "3 times per day"),
                            ("m x,y * * *", "2 times per day"),
                            ("m h * * *", "every day"),
                            ("m h */2 * *", "every 2 days"),
                            ("m h */3 * *", "every 3 days"),
                            ("m h * * d", "selected days"),
                        ],
                        default="m h * * *",
                        help_text="Периодичность выполнения привычки для напоминания в днях.",
                        null=True,
                        verbose_name="Переодичность",
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        help_text="Чем пользователь должен себя вознаградить после выполнения.",
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_needed",
                    models.DurationField(
                        help_text="Время, которое предположительно потратит пользователь на выполнение привычки.",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        help_text="Привычки можно публиковать в общий доступ, чтобы другие пользователи"
                        " могли брать в пример чужие привычки.",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Привычка, которая связана с другой привычкой, важно указывать "
                        "для полезных привычек, но не для приятных.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habit.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
