# Generated by Django 5.2.1 on 2025-06-03 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_execution",
            field=models.DateField(blank=True, null=True, verbose_name="Дата последнего выполнения"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[django.core.validators.MaxValueValidator(7)],
                verbose_name="Периодичность привычки",
            ),
        ),
    ]
