# Generated by Django 5.2.1 on 2025-06-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_habit_last_execution_alter_habit_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=0,
                help_text="Привычки можно публиковать в общий доступ, чтобы другие пользователи могли брать в пример чужие привычки.",
                verbose_name="Признак публичности",
            ),
        ),
    ]
